name: Nightly Generation

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew and others.
      run: chmod +x gradlew *.sh
      
    - name: Download the Engine
      run: ./build_engine.sh
      
    - name: Fix the Engine
      run: ./fix_engine.sh
      
    - name: Build
      run: ./gradlew buildSdk
      
    - name: Build Nightly NBMs
      env:
        NBM_SIGN_PASS: ${{ secrets.NBM_SIGN_PASS }}
      # For Stable, use set-spec-version
      run: ant -Dstorepass="$NBM_SIGN_PASS" set-impl-version suite.nbms unset-impl-version
  
    - name: List potential artifacts
      run: ls -lsh build/ && ls -lsh build/updates
